version: '3'
#
#networks:
#  default:
#    external:
#      name: imooc-network

services:
  message-service:
    image: faker322/message-service:latest

  user-service:
    image: faker322/user-service:latest
    links:
      - message-service
    command:
    - "--mysql.address=121.40.8.72"

  user-edge-service:
    image: faker322/user-edge-service:latest
    links:
    - user-service
    - message-service
    command:
    - "--redis.address=172.31.27.141"
    ports:
      - 8082:8082

  course-service:
    image: faker322/course-service:latest
    links:
    - user-service
    command:
    - "--mysql.address=121.40.8.72"
    - "--zookeeper.address=172.31.27.141"

  course-edge-service:
    image: faker322/course-edge-service:latest
    links:
    - user-edge-service
    command:
    - "--zookeeper.address=172.31.27.141"

  api-gateway-zuul:
    image: faker322/api-gateway-zuul:latest
    links:
#    - course-edge-service
    - user-edge-service
    ports:
    - 80:80

